"use client";

import * as React from "react";
import { botsFor, botById } from "@/lib/office/bots";
import { tx, LOCALE, type Lang } from "@/lib/office/i18n";
import s from "./office.module.css";
import { dailySeries, hourlyToday, lastDays, dayLabel, weekdayShort, isWeekend, sum, avg, fmtInt, fmtK, fmtMoney, Delta, Spark, LineChart, BarChart, Donut, Legend, ChartCard } from "./charts";

type Range = "hoy" | "7d" | "30d";
const rangeLabel = (lang: Lang): Record<Range, string> => {
  const t = tx(lang);
  return { hoy: t("Hoy", "Today"), "7d": t("7 días", "7 days"), "30d": t("30 días", "30 days") };
};
function RangeToggle({ value, onChange, lang }: { value: Range; onChange: (r: Range) => void; lang: Lang }) {
  const labels = rangeLabel(lang);
  return (
    <div className={s.range} role="tablist">
      {(["hoy", "7d", "30d"] as Range[]).map((r) => (
        <button key={r} type="button" role="tab" aria-selected={value === r} className={value === r ? s.on : ""} onClick={() => onChange(r)}>
          {labels[r]}
        </button>
      ))}
    </div>
  );
}
const hourLabels = (lang: Lang) => Array.from({ length: 24 }, (_, h) => (lang === "es" ? `${String(h).padStart(2, "0")}h` : `${String(h).padStart(2, "0")}:00`));
const AREA_COLORS = ["#3b82f6", "#22c55e", "#f59e0b", "#8b5cf6", "#14b8a6"];
const areas = (lang: Lang) => (lang === "es" ? ["Ventas", "Soporte", "Finanzas", "Marketing", "Operaciones"] : ["Sales", "Support", "Finance", "Marketing", "Operations"]);

/** An event reported by the scene (see scene/index.js `emit`). */
export type OfficeEvent = {
  t: number;
  type: "line" | "coffee" | "break" | "back" | "game" | "pingpong" | "print" | "visit" | "meeting" | "task" | "call";
  bot?: string;
  to?: string;
  host?: string;
  place?: string;
  text?: string;
  winner?: string;
  loser?: string;
  score?: string;
  bots?: string[];
  game?: string;
};

export type HotspotMeta = { icon: string; title: string; subtitle: string; color: string };

export function hotspotMeta(lang: Lang): Record<string, HotspotMeta> {
  const t = tx(lang);
  return {
    board: { icon: "📋", title: t("Tablero de tareas", "Task board"), subtitle: t("Qué está haciendo cada empleado IA", "What each AI employee is working on"), color: "#d9f2e6" },
    tv: { icon: "📺", title: t("Dashboard de operaciones", "Operations dashboard"), subtitle: t("Métricas del equipo en vivo", "Live team metrics"), color: "#d6e6ff" },
    coffee: { icon: "☕", title: t("Cafetera", "Coffee machine"), subtitle: t("Consumo del equipo hoy", "Team consumption today"), color: "#ffe3c2" },
    printer: { icon: "🖨️", title: t("Impresora", "Printer"), subtitle: t("Documentos generados por los bots", "Documents generated by the bots"), color: "#e3e0f7" },
    shelf: { icon: "📚", title: t("Base de conocimiento", "Knowledge base"), subtitle: t("Lo que el equipo ha aprendido", "What the team has learned"), color: "#f9d5e5" },
    water: { icon: "💬", title: t("Radio pasillo", "Hallway radio"), subtitle: t("Conversaciones entre los bots", "Conversations between the bots"), color: "#a9dcd3" },
    clock: { icon: "🕒", title: t("Línea de tiempo", "Timeline"), subtitle: t("Todo lo que pasó hoy en la oficina", "Everything that happened in the office today"), color: "#f7c4b6" },
    servers: { icon: "🖥️", title: t("Estado de sistemas", "Systems status"), subtitle: t("Infraestructura de los agentes", "Agent infrastructure"), color: "#b9d7f2" },
    pingpong: { icon: "🏓", title: t("Marcador de ping-pong", "Ping-pong scoreboard"), subtitle: t("Ranking del equipo", "Team ranking"), color: "#c9e8b2" },
    reception: { icon: "🛎️", title: t("Recepción", "Reception"), subtitle: t("Visitas y agenda del día", "Today's visits and schedule"), color: "#ffe3c2" },
    meeting: { icon: "📅", title: t("Agenda de reuniones", "Meetings agenda"), subtitle: t("Sala Andes y Sala Chimborazo", "Andes Room and Chimborazo Room"), color: "#d9c6f2" },
    lounge: { icon: "🛋️", title: t("Rendimiento de los agentes", "Agent performance"), subtitle: t("Carga de trabajo, tokens y costo", "Workload, tokens and cost"), color: "#f4d98a" },
  };
}

/** Where a place id reads as, with its article ("fue a la cafetera" / "went to the coffee machine"). */
const PLACE: Record<Lang, Record<string, string>> = {
  es: {
    coffee: "la cafetera", kitchen: "la cafetería", meeting: "la Sala Andes", meeting2: "la Sala Chimborazo", training: "la capacitación",
    booth: "una cabina", printer: "la impresora", water: "el dispensador", servers: "la sala de servidores", pingpong: "el ping-pong",
    tv: "la pantalla", lounge: "el lounge", beanbag: "el puf", labBoard: "la pizarra del lab", visit: "un escritorio",
  },
  en: {
    coffee: "the coffee machine", kitchen: "the cafeteria", meeting: "the Andes Room", meeting2: "the Chimborazo Room", training: "the training room",
    booth: "a booth", printer: "the printer", water: "the water cooler", servers: "the server room", pingpong: "the ping-pong table",
    tv: "the screen", lounge: "the lounge", beanbag: "the beanbag", labBoard: "the lab whiteboard", visit: "a desk",
  },
};
const placeName = (lang: Lang, place?: string) => PLACE[lang][place ?? ""] ?? place ?? "";
const roomName = (lang: Lang, room: "andes" | "chimborazo") => (lang === "es" ? (room === "andes" ? "Sala Andes" : "Sala Chimborazo") : room === "andes" ? "Andes Room" : "Chimborazo Room");
const botName = (lang: Lang, id?: string) => (id ? botById(lang, id)?.name ?? "" : "");
const hhmm = (t: number, lang: Lang) => new Date(t).toLocaleTimeString(LOCALE[lang], { hour: "2-digit", minute: "2-digit" });
const ago = (t: number, lang: Lang) => {
  const m = Math.round((Date.now() - t) / 60000);
  if (lang === "es") return m < 1 ? "hace un momento" : m === 1 ? "hace 1 min" : `hace ${m} min`;
  return m < 1 ? "just now" : m === 1 ? "1 min ago" : `${m} min ago`;
};

function Avatar({ id, size = 26, lang }: { id: string; size?: number; lang: Lang }) {
  const b = botById(lang, id);
  if (!b) return null;
  return (
    <span className={s.miniAvatar} style={{ background: b.color, width: size, height: size, fontSize: size * 0.45 }} title={b.name}>
      {b.name[0]}
    </span>
  );
}

function useTick(ms: number) {
  const [tick, setTick] = React.useState(0);
  React.useEffect(() => {
    const id = window.setInterval(() => setTick((t) => t + 1), ms);
    return () => window.clearInterval(id);
  }, [ms]);
  return tick;
}

// ------------------------------------------------------------- panels ----
type PanelProps = { events: OfficeEvent[]; status: Record<string, string | null>; onOpenBot: (id: string) => void; lang: Lang };

/** Kanban of what everybody is on; a bot's card moves to "Hecho" each time it finishes a work cycle. */
function BoardPanel({ events, status, onOpenBot, lang }: PanelProps) {
  const t = tx(lang);
  const bots = botsFor(lang);
  const done = React.useMemo(() => {
    const out: { bot: string; text: string; t: number }[] = [];
    const idx: Record<string, number> = {};
    for (const e of [...events].reverse())
      if (e.type === "task" && e.bot) {
        const b = botById(lang, e.bot);
        if (!b) continue;
        idx[e.bot] = (idx[e.bot] ?? 0) + 1;
        out.unshift({ bot: e.bot, text: b.working[idx[e.bot] % b.working.length], t: e.t });
      }
    return out.slice(0, 14);
  }, [events, lang]);
  const doing = bots.map((b) => ({ bot: b.id, text: status[b.id] ?? b.working[0], busy: status[b.id] == null }));
  const todo = bots.flatMap((b) => b.working.slice(1, 3).map((w) => ({ bot: b.id, text: w })));
  const col = (title: string, items: { bot: string; text: string; t?: number; busy?: boolean }[], tone: string) => (
    <div className={s.kanbanCol}>
      <div className={s.kanbanHead}>
        <span className={s.kanbanDot} style={{ background: tone }} />
        {title}
        <b>{items.length}</b>
      </div>
      {items.map((it, i) => (
        <button key={i} type="button" className={s.kanbanCard} onClick={() => onOpenBot(it.bot)}>
          <Avatar id={it.bot} size={20} lang={lang} />
          <span>
            {it.text}
            {it.t && <small>{ago(it.t, lang)}</small>}
            {it.busy === false && <small>{t("en pausa", "on a break")}</small>}
          </span>
        </button>
      ))}
    </div>
  );
  return (
    <div className={s.kanban}>
      {col(t("Por hacer", "To do"), todo.slice(0, 12), "#9ca3af")}
      {col(t("En curso", "In progress"), doing, "#3b82f6")}
      {col(t("Hecho hoy", "Done today"), done, "#22c55e")}
    </div>
  );
}

type Metric = {
  key: string;
  label: string;
  color: string;
  seed: number;
  opts: Parameters<typeof dailySeries>[2];
  agg: "sum" | "avg";
  fmt: (v: number) => string;
  target?: number;
  unit: string;
};
const metrics = (lang: Lang): Metric[] => {
  const t = tx(lang);
  return [
    { key: "leads", label: t("Leads calificados", "Qualified leads"), color: "#3b82f6", seed: 11, opts: { start: 26, drift: 0.008, vol: 0.1, min: 12, max: 80, weekend: 0.72 }, agg: "sum", fmt: (v) => fmtInt(v, lang), target: 35, unit: "leads" },
    { key: "tickets", label: t("Tickets resueltos", "Tickets resolved"), color: "#22c55e", seed: 12, opts: { start: 98, drift: 0.006, vol: 0.07, min: 60, max: 220, weekend: 0.78 }, agg: "sum", fmt: (v) => fmtInt(v, lang), target: 120, unit: "tickets" },
    { key: "revenue", label: t("Cobrado", "Collected"), color: "#f59e0b", seed: 13, opts: { start: 9200, drift: 0.007, vol: 0.16, min: 4000, max: 28000, weekend: 0.7, round: -2 }, agg: "sum", fmt: (v) => fmtMoney(v, lang), unit: "USD" },
    { key: "reach", label: t("Alcance en redes", "Social reach"), color: "#8b5cf6", seed: 14, opts: { start: 36000, drift: 0.008, vol: 0.09, min: 20000, max: 110000, weekend: 0.95, round: -2 }, agg: "avg", fmt: (v) => fmtK(v, lang), unit: t("personas/día", "people/day") },
  ];
};
type Stage = "won" | "negotiation" | "proposal" | "presentation";
const stageLabel = (lang: Lang): Record<Stage, string> => {
  const t = tx(lang);
  return { won: t("Cerrado ganado", "Closed won"), negotiation: t("Negociación", "Negotiation"), proposal: t("Propuesta enviada", "Proposal sent"), presentation: t("Presentación", "Presentation") };
};
const DEALS: { company: string; stage: Stage; amount: number; owner: string; daysAgo: number }[] = [
  { company: "Grupo Andino", stage: "won", amount: 18400, owner: "sofia", daysAgo: 0 },
  { company: "Farmacias Cruz", stage: "negotiation", amount: 9900, owner: "sofia", daysAgo: 1 },
  { company: "Hotel Casa Gangotena", stage: "proposal", amount: 4100, owner: "sofia", daysAgo: 1 },
  { company: "Coop. 29 de Octubre", stage: "won", amount: 6200, owner: "mateo", daysAgo: 2 },
  { company: "Logística del Pacífico", stage: "won", amount: 12750, owner: "sofia", daysAgo: 4 },
  { company: "Universidad del Valle", stage: "presentation", amount: 15200, owner: "sofia", daysAgo: 6 },
];

/** Operations dashboard: KPIs vs. the previous period, a metric over time, work by area, lead sources and recent deals. */
function TvPanel({ events, onOpenBot, lang }: PanelProps) {
  const t = tx(lang);
  const name = (id?: string) => botName(lang, id);
  const bots = botsFor(lang);
  const [range, setRange] = React.useState<Range>("30d");
  const [metricKey, setMetricKey] = React.useState("leads");
  const data = React.useMemo(
    () =>
      metrics(lang).map((m) => {
        const d60 = dailySeries(m.seed, 60, m.opts);
        const hours = hourlyToday(m.seed + 100, d60[59]);
        return { ...m, d60, hours };
      }),
    [lang]
  );
  const days = React.useMemo(() => lastDays(30), []);
  const hours24 = hourLabels(lang);
  const nowH = new Date().getHours();
  const view = (m: (typeof data)[number]) => {
    if (range === "hoy") {
      const cur = m.hours.slice(0, nowH + 1);
      const value = m.agg === "sum" ? sum(cur) : m.d60[59];
      // today vs. the same weekday last week, scaled to the hours elapsed
      const prevValue = m.agg === "sum" ? m.d60[52] * ((nowH + 1) / 24) * 1.15 : m.d60[52];
      return { cur, prev: null as number[] | null, value, prevValue, labels: hours24.slice(0, nowH + 1), weekend: undefined as boolean[] | undefined };
    }
    const n = range === "7d" ? 7 : 30;
    const cur = m.d60.slice(60 - n), prev = m.d60.slice(60 - 2 * n, 60 - n);
    const value = m.agg === "sum" ? sum(cur) : avg(cur);
    const prevValue = m.agg === "sum" ? sum(prev) : avg(prev);
    const ds = days.slice(30 - n);
    return { cur, prev, value, prevValue, labels: ds.map((d) => dayLabel(d, lang)), weekend: ds.map(isWeekend) };
  };
  const sel = data.find((m) => m.key === metricKey) ?? data[0];
  const sv = view(sel);
  const areaNames = areas(lang);
  const areaWeek = React.useMemo(() => {
    const per = AREA_COLORS.map((_, k) => dailySeries(41 + k, 7, { start: 14 + k * 3, vol: 0.25, min: 3, max: 40, weekend: 0.6 }));
    return lastDays(7).map((d, i) => ({ label: weekdayShort(d, lang), values: per.map((p) => p[i]) }));
  }, [lang]);
  const sources = [
    { label: "WhatsApp", value: 412, color: "#25d366" },
    { label: t("Sitio web", "Website"), value: 293, color: "#3b82f6" },
    { label: "Email", value: 206, color: "#f59e0b" },
    { label: t("Referidos", "Referrals"), value: 119, color: "#8b5cf6" },
    { label: t("Eventos", "Events"), value: 54, color: "#14b8a6" },
  ];
  const done = bots.map((b) => ({ id: b.id, n: events.filter((e) => e.type === "task" && e.bot === b.id).length, accent: b.accent }));
  const max = Math.max(1, ...done.map((d) => d.n));
  const stages = stageLabel(lang);
  const prevLabel = t("Periodo anterior", "Previous period");
  return (
    <div className={s.dash}>
      <div className={s.chartHead}>
        <div>
          <div className={s.chartTitle}>
            {t("Resumen", "Summary")} · {rangeLabel(lang)[range].toLowerCase()}
          </div>
          <div className={s.chartSub}>{t("Comparado con el periodo anterior · toca una métrica para verla en el gráfico", "Compared with the previous period · tap a metric to chart it")}</div>
        </div>
        <RangeToggle value={range} onChange={setRange} lang={lang} />
      </div>
      <div className={s.dashGrid}>
        {data.map((m) => {
          const v = view(m);
          return (
            <button key={m.key} type="button" className={`${s.tile} ${metricKey === m.key ? s.tileOn : ""}`} onClick={() => setMetricKey(m.key)}>
              <span className={s.tileTop}>
                {m.label}
                <Delta now={v.value} prev={v.prevValue} lang={lang} />
              </span>
              <b>{m.fmt(v.value)}</b>
              <small>{m.agg === "avg" ? t("promedio diario", "daily average") : range === "hoy" ? t("hasta ahora", "so far") : t("en el periodo", "in the period")}</small>
              <Spark data={v.cur.length > 1 ? v.cur : [0, ...v.cur]} color={m.color} />
            </button>
          );
        })}
      </div>
      <ChartCard
        title={`${sel.label} · ${range === "hoy" ? t("por hora", "hourly") : t("por día", "daily")}`}
        sub={range === "hoy" ? t("hoy, hasta la hora actual", "today, up to the current hour") : `${sel.unit} · ${t("los fines de semana en gris", "weekends in gray")}`}
        right={<Legend items={[{ label: sel.label, color: sel.color }, ...(sv.prev ? [{ label: prevLabel, color: "#9ca3af" }] : [])]} />}
      >
        <LineChart
          series={[{ name: sel.label, color: sel.color, data: sv.cur }, ...(sv.prev ? [{ name: prevLabel, color: "#9ca3af", data: sv.prev, dashed: true, area: false }] : [])]}
          labels={sv.labels}
          weekend={sv.weekend}
          lang={lang}
          yFormat={sel.key === "revenue" || sel.key === "reach" ? (v) => fmtK(v, lang) : (v) => fmtInt(v, lang)}
          target={sel.target && range !== "hoy" ? { value: sel.target, label: t(`meta ${sel.target}/día`, `target ${sel.target}/day`) } : undefined}
        />
      </ChartCard>
      <div className={s.grid2}>
        <ChartCard title={t("Tareas completadas por área", "Tasks completed by area")} sub={t("últimos 7 días", "last 7 days")} right={undefined}>
          <BarChart groups={areaWeek} colors={AREA_COLORS} every={1} height={160} lang={lang} />
          <div style={{ marginTop: 6 }}>
            <Legend items={areaNames.map((a, k) => ({ label: a, color: AREA_COLORS[k] }))} />
          </div>
        </ChartCard>
        <ChartCard title={t("Origen de los leads", "Lead sources")} sub={t("últimos 30 días", "last 30 days")}>
          <Donut parts={sources} size={112} lang={lang} />
        </ChartCard>
      </div>
      <ChartCard title={t("Últimos negocios", "Recent deals")} sub={t("pipeline de ventas · HubSpot", "sales pipeline · HubSpot")}>
        <table className={s.tbl}>
          <thead>
            <tr>
              <th>{t("Empresa", "Company")}</th>
              <th>{t("Etapa", "Stage")}</th>
              <th className={s.num}>{t("Monto", "Amount")}</th>
              <th>{t("Responsable", "Owner")}</th>
              <th>{t("Fecha", "Date")}</th>
            </tr>
          </thead>
          <tbody>
            {DEALS.map((d) => (
              <tr key={d.company} className={s.rowBtn} onClick={() => onOpenBot(d.owner)}>
                <td>{d.company}</td>
                <td>
                  <span className={`${s.tag} ${d.stage === "won" ? s.tagOk : d.stage === "negotiation" ? s.tagWarn : ""}`}>{stages[d.stage]}</span>
                </td>
                <td className={s.num}>{fmtMoney(d.amount, lang)}</td>
                <td>{name(d.owner)}</td>
                <td>{d.daysAgo === 0 ? t("hoy", "today") : d.daysAgo === 1 ? t("ayer", "yesterday") : dayLabel(new Date(Date.now() - d.daysAgo * 86400000), lang)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </ChartCard>
      <div className={s.h}>{t("En vivo · ciclos de trabajo completados por empleado", "Live · work cycles completed per employee")}</div>
      <div className={s.bars2}>
        {done.map((d) => (
          <button key={d.id} type="button" className={s.bar2} onClick={() => onOpenBot(d.id)}>
            <Avatar id={d.id} size={22} lang={lang} />
            <i style={{ width: `${(d.n / max) * 100}%`, background: d.accent }} />
            <b>{d.n}</b>
          </button>
        ))}
      </div>
    </div>
  );
}

function CoffeePanel({ events, onOpenBot, lang }: PanelProps) {
  const t = tx(lang);
  const name = (id?: string) => botName(lang, id);
  const bots = botsFor(lang);
  const hours24 = hourLabels(lang);
  const cups = events.filter((e) => e.type === "coffee");
  const nowH = new Date().getHours();
  const hours = React.useMemo(() => hourlyToday(21, 27, 9.5, 15), []);
  const liveByHour = hours.map((v, h) => Math.round(v) + cups.filter((c) => new Date(c.t).getHours() === h).length);
  const today = sum(liveByHour);
  // the cups poured before you arrived, spread over the team
  const seeded = Math.round(sum(hours.map((v) => Math.round(v))));
  const byBot = bots.map((b, i) => ({ id: b.id, n: Math.floor((seeded * (((i * 7) % 11) + 3)) / 72) + cups.filter((c) => c.bot === b.id).length })).sort((a, b) => b.n - a.n);
  const last = cups[0];
  const twoWeeks = React.useMemo(() => dailySeries(22, 14, { start: 26, vol: 0.18, min: 6, max: 45, weekend: 0.6 }), []);
  const beans = Math.max(8, 78 - today * 1.2);
  return (
    <div className={s.dash}>
      <div className={s.kpis}>
        <div className={s.kpi}>
          <b>{today}</b>
          <span>
            {t("cafés hoy", "coffees today")} <Delta now={today} prev={twoWeeks[6] * ((nowH + 1) / 20)} lang={lang} />
          </span>
        </div>
        <div className={s.kpi}>
          <b>{Math.round(beans)}%</b>
          <span>{t("granos", "beans")}</span>
        </div>
        <div className={s.kpi}>
          <b>{last ? name(last.bot) : "—"}</b>
          <span>{last ? t(`último, ${ago(last.t, lang)}`, `last one, ${ago(last.t, lang)}`) : t("aún nadie", "nobody yet")}</span>
        </div>
      </div>
      <ChartCard title={t("Cafés por hora", "Coffees per hour")} sub={t("hoy · el pico de media mañana y el de después del almuerzo", "today · the mid-morning peak and the after-lunch one")}>
        <BarChart groups={liveByHour.slice(6, Math.max(8, nowH + 1)).map((v, i) => ({ label: hours24[i + 6], values: [v] }))} colors={["#c47a58"]} every={2} height={140} lang={lang} />
      </ChartCard>
      <ChartCard title={t("Cafés por día", "Coffees per day")} sub={t("últimas dos semanas", "last two weeks")} right={<Delta now={sum(twoWeeks.slice(7))} prev={sum(twoWeeks.slice(0, 7))} lang={lang} />}>
        <Spark data={twoWeeks} color="#c47a58" h={48} />
      </ChartCard>
      <div className={s.h}>{t("Ranking de cafeteros · en vivo", "Coffee drinkers ranking · live")}</div>
      <div className={s.list}>
        {byBot.slice(0, 6).map((b, i) => (
          <button key={b.id} type="button" className={s.row2} onClick={() => onOpenBot(b.id)}>
            <span className={s.rank}>{i + 1}</span>
            <Avatar id={b.id} lang={lang} />
            <span className={s.grow}>{name(b.id)}</span>
            <span className={s.cups}>{"☕".repeat(Math.min(6, b.n)) || "·"}</span>
            <b>{b.n}</b>
          </button>
        ))}
      </div>
      <div className={s.note}>
        {t("Máquina lista · agua OK · descalcificación en 12 días", "Machine ready · water OK · descaling in 12 days")} · {fmtInt(1240, lang)} {t("cafés este mes", "coffees this month")}
      </div>
    </div>
  );
}

const docTitles = (lang: Lang): Record<string, string[]> =>
  lang === "es"
    ? {
        sales: ["Propuesta comercial · Grupo Andino.pdf", "Pipeline semanal.pdf"],
        support: ["Resumen de tickets escalados.pdf", "CSAT del mes.pdf"],
        social: ["Calendario de contenido · octubre.pdf", "Reporte de campaña.pdf"],
        dev: ["Notas de despliegue v2.4.pdf", "Reporte de incidentes.pdf"],
        finance: ["Conciliación bancaria · septiembre.pdf", "Flujo de caja 30 días.pdf"],
        ops: ["Pedido de insumos.pdf", "Agenda de la semana.pdf"],
      }
    : {
        sales: ["Sales proposal · Grupo Andino.pdf", "Weekly pipeline.pdf"],
        support: ["Escalated tickets summary.pdf", "Monthly CSAT.pdf"],
        social: ["Content calendar · October.pdf", "Campaign report.pdf"],
        dev: ["Release notes v2.4.pdf", "Incident report.pdf"],
        finance: ["Bank reconciliation · September.pdf", "30-day cash flow.pdf"],
        ops: ["Supplies order.pdf", "Week's agenda.pdf"],
      };
function PrinterPanel({ events, onOpenBot, lang }: PanelProps) {
  const t = tx(lang);
  const name = (id?: string) => botName(lang, id);
  const titles = docTitles(lang);
  const prints = events.filter((e) => e.type === "print");
  const seed = [
    { bot: "camila", title: titles.finance[0], t: Date.now() - 32 * 60000 },
    { bot: "sofia", title: titles.sales[0], t: Date.now() - 58 * 60000 },
  ];
  const docs = [...prints.map((p, i) => ({ bot: p.bot!, title: titles[botById(lang, p.bot!)?.screen ?? "ops"][i % 2], t: p.t })), ...seed];
  return (
    <div className={s.stack}>
      <div className={s.kpis}>
        <div className={s.kpi}>
          <b>{docs.length}</b>
          <span>{t("documentos hoy", "documents today")}</span>
        </div>
        <div className={s.kpi}>
          <b>{docs.length * 7 + 3}</b>
          <span>{t("páginas", "pages")}</span>
        </div>
        <div className={s.kpi}>
          <b>OK</b>
          <span>{t("tóner 64 %", "toner 64%")}</span>
        </div>
      </div>
      <div className={s.h}>{t("Cola de impresión", "Print queue")}</div>
      <div className={s.list}>
        {docs.map((d, i) => (
          <button key={i} type="button" className={s.row2} onClick={() => onOpenBot(d.bot)}>
            <span className={s.docIcon}>PDF</span>
            <span className={s.grow}>
              {d.title}
              <small>
                {name(d.bot)} · {hhmm(d.t, lang)}
              </small>
            </span>
            <Avatar id={d.bot} size={22} lang={lang} />
          </button>
        ))}
      </div>
    </div>
  );
}

const kb = (lang: Lang): { title: string; tags: string[]; by: string; pages: number }[] => {
  const t = tx(lang);
  return [
    { title: t("Manual de atención al cliente", "Customer service handbook"), tags: [t("soporte", "support"), t("tono", "tone")], by: "mateo", pages: 24 },
    { title: t("Política de reembolsos", "Refund policy"), tags: [t("soporte", "support"), t("finanzas", "finance")], by: "camila", pages: 6 },
    { title: t("Guion de calificación de leads", "Lead qualification script"), tags: [t("ventas", "sales")], by: "sofia", pages: 9 },
    { title: t("Guía de marca y voz", "Brand and voice guide"), tags: ["marketing", t("diseño", "design")], by: "valentina", pages: 31 },
    { title: t("Runbook de despliegues", "Deployment runbook"), tags: [t("desarrollo", "dev")], by: "nicolas", pages: 14 },
    { title: t("Catálogo de productos 2026", "2026 product catalog"), tags: [t("ventas", "sales"), t("soporte", "support")], by: "sofia", pages: 42 },
    { title: t("Proveedores y contactos", "Vendors and contacts"), tags: [t("operaciones", "operations")], by: "andres", pages: 11 },
    { title: t("Plantillas de contratos", "Contract templates"), tags: ["legal"], by: "emma", pages: 18 },
    { title: t("Diccionario de datos", "Data dictionary"), tags: [t("datos", "data"), t("desarrollo", "dev")], by: "tomas", pages: 27 },
    { title: t("Proceso de onboarding", "Onboarding process"), tags: [t("talento", "talent")], by: "lucia", pages: 8 },
    { title: t("Protocolo de visitas", "Visitor protocol"), tags: [t("recepción", "reception")], by: "ana", pages: 4 },
  ];
};
function ShelfPanel({ onOpenBot, lang }: PanelProps) {
  const t = tx(lang);
  const name = (id?: string) => botName(lang, id);
  const [q, setQ] = React.useState("");
  const docs = React.useMemo(() => kb(lang), [lang]);
  const list = docs.filter((d) => !q || (d.title + d.tags.join(" ")).toLowerCase().includes(q.toLowerCase()));
  return (
    <div className={s.stack}>
      <input className={s.search} placeholder={t("Buscar en la base de conocimiento…", "Search the knowledge base…")} value={q} onChange={(e) => setQ(e.target.value)} />
      <div className={s.note}>
        {docs.length} {t("documentos", "documents")} · {docs.reduce((a, d) => a + d.pages, 0)} {t("páginas aprendidas por el equipo", "pages learned by the team")}
      </div>
      <div className={s.list}>
        {list.map((d) => (
          <button key={d.title} type="button" className={s.row2} onClick={() => onOpenBot(d.by)}>
            <span className={s.docIcon} style={{ background: "#eef2ff", color: "#4338ca" }}>
              DOC
            </span>
            <span className={s.grow}>
              {d.title}
              <small>
                {d.tags.map((g) => `#${g}`).join(" ")} · {d.pages} {t("págs.", "pp.")} · {t("aprendido por", "learned by")} {name(d.by)}
              </small>
            </span>
            <Avatar id={d.by} size={22} lang={lang} />
          </button>
        ))}
        {!list.length && <div className={s.note}>{t(`Sin resultados para “${q}”.`, `No results for “${q}”.`)}</div>}
      </div>
    </div>
  );
}

/** The bots' own conversations, newest first, grouped by encounter. */
function WaterPanel({ events, onOpenBot, lang }: PanelProps) {
  const t = tx(lang);
  const name = (id?: string) => botName(lang, id);
  const lines = events.filter((e) => e.type === "line");
  const groups: { key: string; place: string; lines: OfficeEvent[] }[] = [];
  for (const l of lines) {
    const pair = [l.bot, l.to].sort().join("+") + ":" + l.place;
    const g = groups[groups.length - 1];
    if (g && g.key === pair && g.lines[g.lines.length - 1].t - l.t < 60000) g.lines.push(l);
    else groups.push({ key: pair, place: l.place ?? "", lines: [l] });
  }
  return (
    <div className={s.stack}>
      {!groups.length && <div className={s.note}>{t("Aún no hay conversaciones. Espera a que alguien vaya por un café… ☕", "No conversations yet. Wait until someone goes for a coffee… ☕")}</div>}
      <div className={s.feed}>
        {groups.slice(0, 12).map((g, i) => (
          <div key={i} className={s.convo}>
            <div className={s.convoHead}>
              {[...new Set(g.lines.flatMap((l) => [l.bot!, l.to!]))].map((id) => (
                <Avatar key={id} id={id} size={22} lang={lang} />
              ))}
              <span>
                {t("en", "at")} {placeName(lang, g.place)} · {hhmm(g.lines[g.lines.length - 1].t, lang)}
              </span>
            </div>
            {[...g.lines].reverse().map((l, k) => (
              <button key={k} type="button" className={s.convoLine} onClick={() => onOpenBot(l.bot!)}>
                <b style={{ color: botById(lang, l.bot!)?.accent }}>{name(l.bot)}</b>
                <span>{l.text}</span>
              </button>
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}

function describe(e: OfficeEvent, lang: Lang): string | null {
  const name = (id?: string) => botName(lang, id);
  const place = placeName(lang, e.place);
  if (lang === "es") {
    switch (e.type) {
      case "coffee": return `${name(e.bot)} se preparó un café`;
      case "break": return e.place === "visit" ? null : `${name(e.bot)} fue a ${place}`;
      case "back": return `${name(e.bot)} volvió a su puesto`;
      case "game": return `${name(e.winner)} le ganó a ${name(e.loser)} en piedra, papel o tijera`;
      case "pingpong": return `${name(e.winner)} ganó el ping-pong ${e.score} a ${name(e.loser)}`;
      case "print": return `${name(e.bot)} imprimió un documento`;
      case "visit": return `${name(e.bot)} pasó por el escritorio de ${name(e.host)}`;
      case "meeting": return `Reunión en ${place}: ${e.bots?.map(name).join(", ")}`;
      case "task": return `${name(e.bot)} completó una tarea`;
      case "call": return `${name(e.bot)} terminó una llamada`;
      default: return null;
    }
  }
  switch (e.type) {
    case "coffee": return `${name(e.bot)} made a coffee`;
    case "break": return e.place === "visit" ? null : `${name(e.bot)} went to ${place}`;
    case "back": return `${name(e.bot)} went back to their desk`;
    case "game": return `${name(e.winner)} beat ${name(e.loser)} at rock, paper, scissors`;
    case "pingpong": return `${name(e.winner)} won at ping-pong ${e.score} against ${name(e.loser)}`;
    case "print": return `${name(e.bot)} printed a document`;
    case "visit": return `${name(e.bot)} stopped by ${name(e.host)}'s desk`;
    case "meeting": return `Meeting at ${place}: ${e.bots?.map(name).join(", ")}`;
    case "task": return `${name(e.bot)} completed a task`;
    case "call": return `${name(e.bot)} finished a call`;
    default: return null;
  }
}
function ClockPanel({ events, onOpenBot, lang }: PanelProps) {
  const t = tx(lang);
  const items = events.map((e) => ({ e, text: describe(e, lang) })).filter((x) => x.text).slice(0, 60);
  return (
    <div className={s.stack}>
      {!items.length && <div className={s.note}>{t("La jornada acaba de empezar.", "The workday has just begun.")}</div>}
      <div className={s.timeline}>
        {items.map(({ e, text }, i) => (
          <button key={i} type="button" className={s.tlItem} onClick={() => (e.bot || e.winner) && onOpenBot((e.bot || e.winner)!)}>
            <time>{hhmm(e.t, lang)}</time>
            <Avatar id={(e.bot || e.winner || e.bots?.[0]) ?? ""} size={20} lang={lang} />
            <span>{text}</span>
          </button>
        ))}
      </div>
    </div>
  );
}

function ServersPanel({ lang }: { lang: Lang }) {
  const t = tx(lang);
  const tick = useTick(1500);
  const hours24 = hourLabels(lang);
  const svc = [
    [t("Agente de ventas", "Sales agent"), "sales-agent", 99.99],
    [t("Agente de soporte", "Support agent"), "support-agent", 99.98],
    [t("Orquestador", "Orchestrator"), "orchestrator", 100],
    [t("API de clientes", "Customers API"), "customers-api", 99.97],
    [t("Base de datos", "Database"), "postgres-01", 100],
    [t("Cola de tareas", "Task queue"), "queue", 99.95],
  ] as const;
  const p50 = React.useMemo(() => dailySeries(31, 24, { start: 92, vol: 0.07, min: 70, max: 130 }), []);
  const p95 = React.useMemo(() => p50.map((v, i) => Math.round(v * 1.75 + ((i * 37) % 23))), [p50]);
  const rpm = React.useMemo(() => hourlyToday(32, 42000, 10.5, 16).map((v) => Math.round(v)), []);
  const nowH = new Date().getHours();
  const nodes = [
    { host: "agents-01", cpu: 34, mem: 61 },
    { host: "agents-02", cpu: 29, mem: 58 },
    { host: "api-01", cpu: 18, mem: 44 },
    { host: "postgres-01", cpu: 12, mem: 72 },
  ].map((n, i) => ({ ...n, cpu: Math.max(4, Math.min(96, n.cpu + Math.round(Math.sin(tick * 0.6 + i) * 5))) }));
  const load = Math.round(avg(nodes.map((n) => n.cpu)));
  return (
    <div className={s.dash}>
      <div className={s.kpis}>
        <div className={s.kpi}>
          <b>{t("99,98 %", "99.98%")}</b>
          <span>{t("uptime 30 días", "30-day uptime")}</span>
        </div>
        <div className={s.kpi}>
          <b>{p95[Math.min(23, nowH)]} ms</b>
          <span>{t("latencia p95 ahora", "p95 latency now")}</span>
        </div>
        <div className={s.kpi}>
          <b>{load}%</b>
          <span>{t("CPU promedio", "average CPU")}</span>
        </div>
      </div>
      <ChartCard title={t("Latencia de los agentes", "Agent latency")} sub={t("últimas 24 horas · milisegundos", "last 24 hours · milliseconds")} right={<Legend items={[{ label: "p50", color: "#3b82f6" }, { label: "p95", color: "#f59e0b" }]} />}>
        <LineChart series={[{ name: "p50", color: "#3b82f6", data: p50 }, { name: "p95", color: "#f59e0b", data: p95, area: false }]} labels={hours24} every={4} height={160} yFormat={(v) => `${Math.round(v)}`} target={{ value: 250, label: "SLA 250 ms" }} lang={lang} />
      </ChartCard>
      <ChartCard title={t("Peticiones por hora", "Requests per hour")} sub={t("hoy", "today")}>
        <BarChart groups={rpm.slice(0, Math.max(6, nowH + 1)).map((v, i) => ({ label: hours24[i], values: [v] }))} colors={["#7cc0ff"]} every={3} height={130} yFormat={(v) => fmtK(v, lang)} lang={lang} />
      </ChartCard>
      <ChartCard title={t("Nodos", "Nodes")} sub={t("carga en vivo", "live load")}>
        <table className={s.tbl}>
          <thead>
            <tr>
              <th>Host</th>
              <th>CPU</th>
              <th>{t("Memoria", "Memory")}</th>
              <th className={s.num}>{t("Estado", "Status")}</th>
            </tr>
          </thead>
          <tbody>
            {nodes.map((n) => (
              <tr key={n.host}>
                <td style={{ fontFamily: "var(--mono)", fontSize: 11 }}>{n.host}</td>
                <td>
                  <span className={s.statusLine}>
                    <span className={s.meter}>
                      <i style={{ width: `${n.cpu}%`, background: n.cpu > 80 ? "#ef4444" : "#3b82f6" }} />
                    </span>
                    {n.cpu}%
                  </span>
                </td>
                <td>
                  <span className={s.statusLine}>
                    <span className={s.meter}>
                      <i style={{ width: `${n.mem}%`, background: "#8b5cf6" }} />
                    </span>
                    {n.mem}%
                  </span>
                </td>
                <td className={s.num}>
                  <span className={`${s.tag} ${s.tagOk}`}>OK</span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </ChartCard>
      <div className={s.h}>{t("Servicios", "Services")}</div>
      <div className={s.list}>
        {svc.map(([label, host, up]) => (
          <div key={host} className={s.row2}>
            <span className={s.ledDot} style={{ background: up === 100 ? "#22c55e" : "#84cc16" }} />
            <span className={s.grow}>
              {label}
              <small>{host}</small>
            </span>
            <b>{lang === "es" ? `${up.toFixed(2)} %` : `${up.toFixed(2)}%`}</b>
          </div>
        ))}
      </div>
      <div className={s.note}>
        {t(
          "0 incidentes en 30 días · último: hace 23 días, 4 min de degradación · último despliegue hace 41 min (Nicolás)",
          "0 incidents in 30 days · last one: 23 days ago, 4 min of degradation · last deploy 41 min ago (Nicolás)"
        )}
      </div>
    </div>
  );
}

function PingpongPanel({ events, onOpenBot, lang }: PanelProps) {
  const t = tx(lang);
  const name = (id?: string) => botName(lang, id);
  const games = events.filter((e) => e.type === "pingpong");
  const rps = events.filter((e) => e.type === "game");
  const table = botsFor(lang)
    .map((b) => ({
      id: b.id,
      w: games.filter((g) => g.winner === b.id).length + rps.filter((g) => g.winner === b.id).length,
      l: games.filter((g) => g.loser === b.id).length + rps.filter((g) => g.loser === b.id).length,
    }))
    .filter((r) => r.w + r.l)
    .sort((a, b) => b.w - a.w || a.l - b.l);
  return (
    <div className={s.stack}>
      <div className={s.kpis}>
        <div className={s.kpi}>
          <b>{games.length}</b>
          <span>{t("partidas de ping-pong", "ping-pong games")}</span>
        </div>
        <div className={s.kpi}>
          <b>{rps.length}</b>
          <span>{t("piedra, papel o tijera", "rock, paper, scissors")}</span>
        </div>
        <div className={s.kpi}>
          <b>{table[0] ? name(table[0].id) : "—"}</b>
          <span>{t("líder", "leader")}</span>
        </div>
      </div>
      <div className={s.h}>{t("Ranking", "Ranking")}</div>
      <div className={s.list}>
        {!table.length && <div className={s.note}>{t("Todavía no hay partidas. Alguien caerá pronto… 🏓", "No games yet. Someone will fall soon… 🏓")}</div>}
        {table.map((r, i) => (
          <button key={r.id} type="button" className={s.row2} onClick={() => onOpenBot(r.id)}>
            <span className={s.rank}>{i + 1}</span>
            <Avatar id={r.id} lang={lang} />
            <span className={s.grow}>{name(r.id)}</span>
            <b>
              {r.w} {t("G", "W")} · {r.l} {t("P", "L")}
            </b>
          </button>
        ))}
      </div>
      <div className={s.h}>{t("Últimas partidas", "Latest games")}</div>
      <div className={s.list}>
        {games.slice(0, 6).map((g, i) => (
          <div key={i} className={s.row2}>
            <Avatar id={g.winner!} size={22} lang={lang} />
            <span className={s.grow}>
              <b>{name(g.winner)}</b> {t("venció a", "beat")} {name(g.loser)}{" "}
              <small>
                {g.score} · {hhmm(g.t, lang)}
              </small>
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

function ReceptionPanel({ onOpenBot, lang }: PanelProps) {
  const t = tx(lang);
  const name = (id?: string) => botName(lang, id);
  const now = new Date();
  const h = now.getHours();
  const agenda = [
    { time: "09:00", who: "Grupo Andino", what: t("Demo del agente de ventas", "Sales agent demo"), host: "sofia" },
    { time: "11:30", who: t("Equipo interno", "Internal team"), what: t("Revisión semanal", "Weekly review"), host: "andres" },
    { time: "15:00", who: "Farmacias Cruz", what: t("Presentación de propuesta", "Proposal presentation"), host: "sofia" },
    { time: "16:30", who: "Cooperativa 29 de Octubre", what: "Onboarding", host: "mateo" },
  ];
  const days = React.useMemo(() => lastDays(14), []);
  const visits = React.useMemo(() => dailySeries(51, 14, { start: 8, vol: 0.3, min: 2, max: 18, weekend: 0.5 }), []);
  const calls = React.useMemo(() => dailySeries(52, 14, { start: 29, vol: 0.2, min: 8, max: 55, weekend: 0.55 }), []);
  return (
    <div className={s.dash}>
      <div className={s.kpis}>
        <div className={s.kpi}>
          <b>{visits[13]}</b>
          <span>
            {t("visitantes hoy", "visitors today")} <Delta now={visits[13]} prev={visits[6]} lang={lang} />
          </span>
        </div>
        <div className={s.kpi}>
          <b>{calls[13]}</b>
          <span>
            {t("llamadas", "calls")} <Delta now={calls[13]} prev={calls[6]} lang={lang} />
          </span>
        </div>
        <div className={s.kpi}>
          <b>3</b>
          <span>{t("paquetes", "packages")}</span>
        </div>
      </div>
      <ChartCard title={t("Visitas y llamadas por día", "Visits and calls per day")} sub={t("últimas dos semanas", "last two weeks")} right={<Legend items={[{ label: t("Visitas", "Visits"), color: "#e08a5c" }, { label: t("Llamadas", "Calls"), color: "#3d4a7a" }]} />}>
        <BarChart groups={days.map((d, i) => ({ label: dayLabel(d, lang), values: [visits[i], calls[i]] }))} colors={["#e08a5c", "#3d4a7a"]} stacked={false} every={2} height={150} lang={lang} />
      </ChartCard>
      <div className={s.h}>{t("Agenda de visitas", "Visitor schedule")}</div>
      <div className={s.list}>
        {agenda.map((a) => {
          const past = parseInt(a.time) < h;
          return (
            <button key={a.time} type="button" className={s.row2} onClick={() => onOpenBot(a.host)} style={{ opacity: past ? 0.55 : 1 }}>
              <time className={s.tlTime}>{a.time}</time>
              <span className={s.grow}>
                {a.who}
                <small>
                  {a.what} · {t("recibe", "hosted by")} {name(a.host)}
                </small>
              </span>
              <span className={`${s.tag} ${past ? s.tagOk : s.tagAcc}`}>{past ? t("Atendida", "Done") : t("Confirmada", "Confirmed")}</span>
            </button>
          );
        })}
      </div>
      <div className={s.note}>{t("Atiende Ana · registro con cédula · Wi-Fi de invitados: Wilson-Guest", "Ana at the front desk · sign in with ID · Guest Wi-Fi: Wilson-Guest")}</div>
    </div>
  );
}

const MEET_HIST = dailySeries(61, 14, { start: 5, vol: 0.35, min: 1, max: 11, weekend: 0.4 });
function MeetingPanel({ events, status, onOpenBot, lang }: PanelProps) {
  const t = tx(lang);
  const name = (id?: string) => botName(lang, id);
  const inRoom = botsFor(lang).filter((b) => /Andes|Chimborazo|reunión|meeting/i.test(status[b.id] ?? ""));
  const meetings = events.filter((e) => e.type === "meeting").slice(0, 6);
  const planned: { time: string; room: "andes" | "chimborazo"; title: string; who: string[] }[] = [
    { time: "10:00", room: "andes", title: "Sprint review", who: ["nicolas", "diego", "andres"] },
    { time: "12:00", room: "chimborazo", title: t("Pipeline Q4", "Q4 pipeline"), who: ["sofia", "camila"] },
    { time: "15:00", room: "andes", title: t("Demo Farmacias Cruz", "Farmacias Cruz demo"), who: ["sofia", "mateo", "emma"] },
    { time: "17:00", room: "chimborazo", title: t("Retro semanal", "Weekly retro"), who: ["lucia", "valentina", "tomas"] },
  ];
  return (
    <div className={s.stack}>
      <div className={s.h}>{t("Ahora en las salas", "In the rooms now")}</div>
      {!inRoom.length && <div className={s.note}>{t("Las salas están libres.", "The rooms are free.")}</div>}
      <div className={s.avatarRow}>
        {inRoom.map((b) => (
          <button key={b.id} type="button" className={s.avatarBtn} onClick={() => onOpenBot(b.id)}>
            <Avatar id={b.id} size={30} lang={lang} />
            <small>{b.name}</small>
          </button>
        ))}
      </div>
      <ChartCard title={t("Reuniones por día", "Meetings per day")} sub={t("últimas dos semanas · Sala Andes y Sala Chimborazo", "last two weeks · Andes Room and Chimborazo Room")}>
        <BarChart groups={lastDays(14).map((d, i) => ({ label: dayLabel(d, lang), values: [MEET_HIST[i]] }))} colors={["#6f5a9e"]} every={2} height={120} lang={lang} />
      </ChartCard>
      <div className={s.h}>{t("Reuniones de hoy", "Today's meetings")}</div>
      <div className={s.list}>
        {planned.map((m) => (
          <div key={m.time} className={s.row2}>
            <time className={s.tlTime}>{m.time}</time>
            <span className={s.grow}>
              {m.title}
              <small>{roomName(lang, m.room)}</small>
            </span>
            <span className={s.avatarStack}>
              {m.who.map((id) => (
                <Avatar key={id} id={id} size={20} lang={lang} />
              ))}
            </span>
          </div>
        ))}
      </div>
      {meetings.length > 0 && (
        <>
          <div className={s.h}>{t("Reuniones espontáneas", "Impromptu meetings")}</div>
          <div className={s.list}>
            {meetings.map((m, i) => (
              <div key={i} className={s.row2}>
                <time className={s.tlTime}>{hhmm(m.t, lang)}</time>
                <span className={s.grow}>
                  {m.bots?.map(name).join(", ")}
                  <small>{placeName(lang, m.place)}</small>
                </span>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );
}

function LoungePanel({ events, status, onOpenBot, lang }: PanelProps) {
  const t = tx(lang);
  const name = (id?: string) => botName(lang, id);
  const bots = botsFor(lang);
  // agents do not rest: what matters is their load, what they consume and what they cost
  const tasks = events.filter((e) => e.type === "task");
  const tokens30 = React.useMemo(() => dailySeries(71, 30, { start: 186, drift: 0.004, vol: 0.1, min: 60, max: 420, weekend: 0.72 }), []); // thousands
  const days = React.useMemo(() => lastDays(30), []);
  const perAgent = React.useMemo(() => botsFor(lang).map((b, i) => ({ id: b.id, tokens: Math.round(12 + ((i * 37) % 29) + (i === 1 ? 26 : 0)) })), [lang]);
  const rows = bots.map((b, i) => {
    const done = 18 + ((i * 7) % 11) + tasks.filter((e) => e.bot === b.id).length;
    const load = Math.max(22, Math.min(96, 58 + ((i * 13) % 31) + (status[b.id] == null ? 12 : 0)));
    return { id: b.id, done, load };
  });
  const PRICE = 0.0042; // USD per thousand tokens, blended
  const monthTokens = sum(tokens30);
  const cost30 = monthTokens * PRICE;
  const cost30prev = sum(dailySeries(72, 30, { start: 182, drift: 0.002, vol: 0.1, min: 60, max: 400, weekend: 0.72 })) * PRICE;
  const areaNames = areas(lang);
  // areas(): 0 sales, 1 support, 2 finance, 3 marketing, 4 operations
  const areaCost = [
    { label: areaNames[1], value: cost30 * 0.34, color: "#22c55e" },
    { label: areaNames[0], value: cost30 * 0.27, color: "#3b82f6" },
    { label: areaNames[3], value: cost30 * 0.16, color: "#8b5cf6" },
    { label: areaNames[2], value: cost30 * 0.13, color: "#f59e0b" },
    { label: areaNames[4], value: cost30 * 0.1, color: "#14b8a6" },
  ];
  return (
    <div className={s.dash}>
      <div className={s.kpis}>
        <div className={s.kpi}>
          <b>{rows.reduce((a, r) => a + r.done, 0)}</b>
          <span>{t("tareas hoy", "tasks today")}</span>
        </div>
        <div className={s.kpi}>
          <b>{fmtInt(tokens30[29], lang)}k</b>
          <span>
            {t("tokens hoy", "tokens today")} <Delta now={tokens30[29]} prev={tokens30[22]} invert lang={lang} />
          </span>
        </div>
        <div className={s.kpi}>
          <b>{fmtMoney(cost30, lang)}</b>
          <span>
            {t("costo 30 días", "30-day cost")} <Delta now={cost30} prev={cost30prev} invert lang={lang} />
          </span>
        </div>
      </div>
      <ChartCard title={t("Tokens consumidos por día", "Tokens consumed per day")} sub={t("últimos 30 días · miles de tokens · los fines de semana en gris", "last 30 days · thousands of tokens · weekends in gray")}>
        <LineChart series={[{ name: "Tokens (k)", color: "#6f5a9e", data: tokens30 }]} labels={days.map((d) => dayLabel(d, lang))} weekend={days.map(isWeekend)} height={170} yFormat={(v) => `${Math.round(v)}k`} lang={lang} />
      </ChartCard>
      <div className={s.grid2}>
        <ChartCard title={t("Tokens por agente", "Tokens per agent")} sub={t("hoy · miles", "today · thousands")}>
          <BarChart groups={perAgent.map((a) => ({ label: name(a.id).slice(0, 3), values: [a.tokens] }))} colors={["#6f5a9e"]} every={1} height={150} lang={lang} />
        </ChartCard>
        <ChartCard title={t("Costo por área", "Cost by area")} sub={t("últimos 30 días", "last 30 days")}>
          <Donut parts={areaCost} size={108} format={(v) => fmtMoney(v, lang)} lang={lang} />
        </ChartCard>
      </div>
      <div className={s.h}>{t("Carga de trabajo por agente · en vivo", "Workload per agent · live")}</div>
      <div className={s.bars2}>
        {rows.map((r) => (
          <button key={r.id} type="button" className={s.bar2} onClick={() => onOpenBot(r.id)}>
            <Avatar id={r.id} size={22} lang={lang} />
            <i style={{ width: `${r.load}%`, background: r.load > 85 ? "#f59e0b" : "#22c55e" }} />
            <b>
              {r.load}% · {r.done}
            </b>
          </button>
        ))}
      </div>
      <div className={s.note}>
        {t(
          "Uptime 99,98 % · sin pausas ni vacaciones · un humano aprueba lo que necesita firma · el equivalente humano costaría unas 40 veces más. Cifras simuladas para la demo.",
          "Uptime 99.98% · no breaks or vacations · a human approves whatever needs a signature · the human equivalent would cost about 40x more. Simulated figures for the demo."
        )}
      </div>
    </div>
  );
}

export function HotspotPanel({ id, ...rest }: { id: string } & PanelProps) {
  switch (id) {
    case "board": return <BoardPanel {...rest} />;
    case "tv": return <TvPanel {...rest} />;
    case "coffee": return <CoffeePanel {...rest} />;
    case "printer": return <PrinterPanel {...rest} />;
    case "shelf": return <ShelfPanel {...rest} />;
    case "water": return <WaterPanel {...rest} />;
    case "clock": return <ClockPanel {...rest} />;
    case "servers": return <ServersPanel lang={rest.lang} />;
    case "pingpong": return <PingpongPanel {...rest} />;
    case "reception": return <ReceptionPanel {...rest} />;
    case "meeting": return <MeetingPanel {...rest} />;
    case "lounge": return <LoungePanel {...rest} />;
    default: return null;
  }
}
